# Generated by Django 5.1.6 on 2025-02-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appleuser',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='appleuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
